{% set tpl = ix_lib.base.render.Render(values) %}

{% set c1 = tpl.add_container(values.consts.restic_manager_container_name, "image") %}

{% do c1.set_user(0, 0) %}
{% do c1.healthcheck.set_custom_test(["CMD", "/usr/local/bin/truenas-restic-manager", "healthcheck"]) %}
{% do c1.add_extra_host("host.docker.internal", "host-gateway") %}

{% do c1.environment.add_env("TRM_TRUENAS_API_URL", values.restic_manager.truenas_api_url) %}
{% do c1.environment.add_env("TRM_LISTEN", ":%d" | format(values.network.web_port.port_number)) %}
{% if values.restic_manager.upstream_trusted_address %}
  {% do c1.environment.add_env("TRM_UPSTREAM_TRUSTED_ADDRESS", values.restic_manager.upstream_trusted_address | join(",")) %}
{% endif %}
{% do c1.environment.add_env("TRM_API_USER", values.consts.api_user) %}
{% do c1.environment.add_env("TRM_APP_ID", values.consts.app_id) %}
{% do c1.environment.add_env("TRM_API_KEY_NAME", values.consts.api_key_name) %}
{% do c1.environment.add_env("TRM_APP_MOUNTS_PROPERTY", "storage.dataset_mounts") %}
{% do c1.environment.add_env("TRM_STORE_MIGRATE_ON_START", true) %}
{% do c1.environment.add_env("TRM_WORKDIR", "/work") %}
{% do c1.environment.add_env("TRM_STORE_PATH", "/data/store.db") %}
{% do c1.environment.add_env("RESTIC_CACHE_DIR", "/cache") %}
{% do c1.environment.add_user_envs(values.restic_manager.additional_envs) %}

{% do c1.add_port(values.network.web_port) %}

{% do c1.add_storage("/data", values.storage.data) %}
{% do c1.add_storage("/cache", values.storage.cache) %}
{% do c1.add_storage("/work", values.storage.work) %}

{% for store in values.storage.dataset_mounts %}
  {% set dataset_path = store.host_path_config.path or store.mount_path %}
  {% set dataset_store = {
    "type": "host_path",
    "read_only": true,
    "mount_path": dataset_path,
    "host_path_config": {
      "acl_enable": false,
      "path": dataset_path,
      "propagation": "rslave",
    },
  } %}
  {% do c1.add_storage(dataset_path, dataset_store) %}
{% endfor %}

{% do tpl.portals.add(values.network.web_port, {"scheme": "https"}) %}

{{ tpl.render() | tojson }}
