images:
  image:
    repository: codeberg.org/echocat/truenas-restic-manager
    tag: v0.2.1

consts:
  restic_manager_container_name: restic-manager
  app_id: restic-manager
  api_user: restic-manager
  api_key_name: restic-manager
